- name: Create Directory structure
  file: state=directory path={{ download_folder }}

- name: Download Java
  get_url:
    url: "{{ jdk_tarball_url }}"
    dest: "{{ java_archive }}"
    headers: "Cookie: oraclelicense=accept-securebackup-cookie"

- name: Untar JDK
  unarchive:
    src: "{{ java_archive }}"
    dest: "{{ download_folder }}"

- name: Clean up
  file: state=absent path={{java_archive}}
