- name: Install JDK8 on centos
  include_tasks: centos.yml
  when: ansible_distribution == "CentOS"

- name: Install JDK8 on Windows
  include_tasks: windows.yml
  when: ansible_os_family == "Windows"



