---

- name: Getting system facts
  hosts: localhost

  tasks:

  - debug:
      msg: hostname is "{{ ansible_hostname }}"

  - debug:
      msg: os family is "{{ ansible_os_family }}"

  - debug:
      msg: mac address is "{{ ansible_default_ipv4.macaddress }}"

  - debug:
      msg: ip address is "{{ ansible_default_ipv4.address }}"

  - debug:
      msg: os family is "{{ ansible_distribution }}"
