name: Ansible Lint Check

on:
  pull_request:
    branches:
      - "**"

jobs:
  ansible-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout pull request code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Ansible and Ansible Lint
        run: |
          python -m pip install --upgrade pip
          pip install ansible ansible-lint

      - name: Run Ansible Lint
        run: |
          ansible-lint -p ./
